# Generated by Django 4.2.5 on 2023-09-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectStatus', models.BooleanField(default=False)),
                ('adminAdvice', models.BooleanField(default=False)),
                ('projectTitle', models.CharField(max_length=255)),
                ('projectPlace', models.CharField(max_length=255)),
                ('estimatedImplementationDate', models.DateTimeField()),
                ('slogan', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('goal', models.TextField()),
                ('support', models.TextField()),
                ('shortDesc', models.CharField(max_length=200)),
                ('longDesc', models.TextField()),
                ('projectImage', models.ImageField(upload_to='project_images/')),
                ('createdByName', models.CharField(blank=True, max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('participantCount', models.PositiveIntegerField(default=0)),
                ('projectValue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('totalShares', models.PositiveIntegerField(default=0)),
                ('shareValue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('maxSharesPerPerson', models.PositiveIntegerField(default=0)),
                ('sharesTaken', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
