# Generated by Django 4.2.5 on 2023-09-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectValue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='shareValue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
